import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { PageHeader } from "@/components/page-header";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ArticleStageBadge } from "@/components/stage-badge";
import { ArticleEditor } from "@/components/article-editor";
import { setArticleStage, revokePrivateLink } from "@/lib/actions/article";
import { formatDateTime, formatRelative } from "@/lib/utils";
import { enqueueJob } from "@/lib/jobs";
import { requireUser } from "@/lib/auth";
import { revalidatePath } from "next/cache";
import { NewLinkButton } from "./article-actions";

export const dynamic = "force-dynamic";

async function regenerate(articleId: string) {
  "use server";
  await requireUser();
  await enqueueJob("n8n_draft", { articleId }, { idempotencyKey: `draft:${articleId}:${Date.now()}` });
  await prisma.article.update({ where: { id: articleId }, data: { stage: "DRAFT" } });
  revalidatePath(`/articles/${articleId}`);
}

export default async function ArticlePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const article = await prisma.article.findUnique({
    where: { id },
    include: {
      business: true,
      topic: true,
      versions: { orderBy: { version: "desc" } },
      links: { orderBy: { createdAt: "desc" } },
    },
  });
  if (!article) notFound();

  const current = article.versions.find((v) => v.id === article.currentVersionId) ?? article.versions[0];
  const brief = article.researchBrief as {
    summary?: string;
    sources?: { url: string; title?: string; note?: string }[];
    claimsToVerify?: string[];
    internalLinks?: { url: string; anchor?: string }[];
    competingUrls?: string[];
  } | null;
  const feedback = await prisma.feedback.findMany({
    where: { articleVersion: { articleId: article.id } },
    orderBy: { submittedAt: "desc" },
    include: { articleVersion: true, privateLink: true },
  });

  const editable = ["HUMAN_EDIT", "REVISIONS", "CLIENT_REVIEW"].includes(article.stage);

  return (
    <div>
      <PageHeader
        title={article.title}
        description={
          <>
            for{" "}
            <Link href={`/prospects/${article.businessId}`} className="text-primary hover:underline">
              {article.business.name}
            </Link>
          </>
        }
        actions={
          <div className="flex items-center gap-2">
            {article.isFreeOffer && <Badge variant="outline">free article</Badge>}
            <ArticleStageBadge stage={article.stage} />
          </div>
        }
      />
      <div className="grid gap-6 p-8 lg:grid-cols-[1fr_340px]">
        <div className="space-y-6">
          {article.stage === "RESEARCH" && (
            <Card><CardContent className="py-4 text-sm text-muted-foreground">Research brief is being generated by n8n…</CardContent></Card>
          )}
          {article.stage === "DRAFT" && (
            <Card><CardContent className="py-4 text-sm text-muted-foreground">Draft is being generated by n8n…</CardContent></Card>
          )}

          {brief && (
            <Card>
              <CardHeader><CardTitle className="text-sm font-medium">Research brief</CardTitle></CardHeader>
              <CardContent className="space-y-3 text-sm">
                {brief.summary && <p>{brief.summary}</p>}
                {brief.claimsToVerify && brief.claimsToVerify.length > 0 && (
                  <div className="rounded-md border border-amber-300 bg-amber-50 p-3">
                    <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-amber-800">Claims needing human verification</p>
                    <ul className="list-inside list-disc space-y-0.5 text-amber-900">
                      {brief.claimsToVerify.map((c, i) => <li key={i}>{c}</li>)}
                    </ul>
                  </div>
                )}
                {brief.sources && brief.sources.length > 0 && (
                  <div>
                    <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Sources</p>
                    <ul className="space-y-1">
                      {brief.sources.map((s, i) => (
                        <li key={i} className="text-xs">
                          <a href={s.url} target="_blank" rel="noreferrer" className="text-primary hover:underline">{s.title ?? s.url}</a>
                          {s.note && <span className="text-muted-foreground"> — {s.note}</span>}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {brief.internalLinks && brief.internalLinks.length > 0 && (
                  <div>
                    <p className="mb-1 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Suggested internal links</p>
                    <ul className="list-inside list-disc text-xs">
                      {brief.internalLinks.map((l, i) => <li key={i}>{l.anchor ? `"${l.anchor}" → ` : ""}{l.url}</li>)}
                    </ul>
                  </div>
                )}
              </CardContent>
            </Card>
          )}

          {current ? (
            <ArticleEditor
              articleId={article.id}
              title={current.title}
              contentHtml={current.contentHtml}
              editable={editable}
            />
          ) : (
            <Card><CardContent className="py-8 text-center text-sm text-muted-foreground">No content yet — the draft will appear here once generated.</CardContent></Card>
          )}
        </div>

        <div className="space-y-4">
          <Card>
            <CardHeader><CardTitle className="text-sm font-medium">Workflow</CardTitle></CardHeader>
            <CardContent className="flex flex-col gap-2">
              {article.stage === "HUMAN_EDIT" && (
                <>
                  <form action={setArticleStage.bind(null, article.id, "APPROVED")}>
                    <Button type="submit" className="w-full">Mark ready for delivery</Button>
                  </form>
                  <form action={regenerate.bind(null, article.id)}>
                    <Button type="submit" variant="outline" className="w-full">Regenerate draft (new version)</Button>
                  </form>
                </>
              )}
              {article.stage === "REVISIONS" && (
                <form action={setArticleStage.bind(null, article.id, "HUMAN_EDIT")}>
                  <Button type="submit" variant="secondary" className="w-full">Back to editing</Button>
                </form>
              )}
              {article.stage === "APPROVED" && (
                <>
                  <p className="text-xs text-muted-foreground">Ready — create a link and include it in outreach.</p>
                  <form action={setArticleStage.bind(null, article.id, "DELIVERED")}>
                    <Button type="submit" variant="secondary" className="w-full">Mark delivered</Button>
                  </form>
                </>
              )}
            </CardContent>
          </Card>

          <Card>
            <CardHeader className="flex-row items-center justify-between">
              <CardTitle className="text-sm font-medium">Private links</CardTitle>
              <NewLinkButton articleId={article.id} disabled={!current} />
            </CardHeader>
            <CardContent className="space-y-2">
              {article.links.length === 0 && <p className="text-xs text-muted-foreground">No links yet.</p>}
              {article.links.map((l) => (
                <div key={l.id} className="rounded-md border p-2.5 text-xs">
                  <div className="flex items-center justify-between">
                    <span>v{l.articleVersionId === l.articleVersionId ? article.versions.find((v) => v.id === l.articleVersionId)?.version : "?"} link · {l.viewCount} views</span>
                    {l.revokedAt ? <Badge variant="destructive">revoked</Badge> : <Badge variant="secondary">active</Badge>}
                  </div>
                  <div className="mt-1 text-muted-foreground">created {formatRelative(l.createdAt)}{l.lastViewedAt ? ` · last viewed ${formatRelative(l.lastViewedAt)}` : ""}</div>
                  <div className="mt-1.5 flex items-center gap-3">
                    {!l.revokedAt && (
                      <form action={revokePrivateLink.bind(null, l.id)}>
                        <Button type="submit" size="sm" variant="ghost" className="h-6 px-2 text-xs">Revoke</Button>
                      </form>
                    )}

                  </div>
                </div>
              ))}
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle className="text-sm font-medium">Client feedback</CardTitle></CardHeader>
            <CardContent className="space-y-2">
              {feedback.length === 0 && <p className="text-xs text-muted-foreground">None yet.</p>}
              {feedback.map((f) => (
                <div key={f.id} className="rounded-md border p-2.5 text-xs">
                  <div className="mb-1 text-muted-foreground">
                    v{f.articleVersion.version} · {f.contactName ?? "client"} · {formatDateTime(f.submittedAt)}
                  </div>
                  {f.body}
                </div>
              ))}
            </CardContent>
          </Card>

          <Card>
            <CardHeader><CardTitle className="text-sm font-medium">Versions</CardTitle></CardHeader>
            <CardContent className="space-y-1.5 text-xs">
              {article.versions.map((v) => (
                <div key={v.id} className="flex items-center justify-between rounded border px-2.5 py-1.5">
                  <span>v{v.version} · {v.origin.replaceAll("_", " ").toLowerCase()}</span>
                  <span className="text-muted-foreground">{formatRelative(v.createdAt)}</span>
                </div>
              ))}
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
